[project]
name = "django-setup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "django-environ>=0.12.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
