# Generated by Django 5.2 on 2025-05-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price_greater_than_zero_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='product',
            name='price_greater_than_zero',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_greater_than_zero', violation_error_message='Price must be greater than zero'),
        ),
        migrations.AlterConstraint(
            model_name='product',
            name='stock_count_greater_than_zero',
            constraint=models.CheckConstraint(condition=models.Q(('stock_count__gt', 0)), name='stock_count_greater_than_zero', violation_error_message='Stock Count must be greater than zero'),
        ),
    ]
